package com.yzw.platform.entity.user;

public class InfoPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.p_id
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.p_url
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    private String pUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.p_name
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.p_code
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    private String pCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.p_type
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    private Integer pType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.p_parent_id
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    private Integer pParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.p_status
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    private Integer pStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.p_id
     *
     * @return the value of t_permission.p_id
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.p_id
     *
     * @param pId the value for t_permission.p_id
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.p_url
     *
     * @return the value of t_permission.p_url
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public String getpUrl() {
        return pUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.p_url
     *
     * @param pUrl the value for t_permission.p_url
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public void setpUrl(String pUrl) {
        this.pUrl = pUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.p_name
     *
     * @return the value of t_permission.p_name
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.p_name
     *
     * @param pName the value for t_permission.p_name
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public void setpName(String pName) {
        this.pName = pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.p_code
     *
     * @return the value of t_permission.p_code
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.p_code
     *
     * @param pCode the value for t_permission.p_code
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public void setpCode(String pCode) {
        this.pCode = pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.p_type
     *
     * @return the value of t_permission.p_type
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public Integer getpType() {
        return pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.p_type
     *
     * @param pType the value for t_permission.p_type
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public void setpType(Integer pType) {
        this.pType = pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.p_parent_id
     *
     * @return the value of t_permission.p_parent_id
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public Integer getpParentId() {
        return pParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.p_parent_id
     *
     * @param pParentId the value for t_permission.p_parent_id
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public void setpParentId(Integer pParentId) {
        this.pParentId = pParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.p_status
     *
     * @return the value of t_permission.p_status
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public Integer getpStatus() {
        return pStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.p_status
     *
     * @param pStatus the value for t_permission.p_status
     *
     * @mbg.generated Fri Jul 12 17:25:45 CST 2019
     */
    public void setpStatus(Integer pStatus) {
        this.pStatus = pStatus;
    }
}