package com.yzw.platform.entity.user;

import java.io.Serializable;
import java.util.Date;

public class InfoStreet implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.id
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.area_id
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.code
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.name
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.create_user
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.create_time
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.create_ip
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private String createIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.update_user
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.update_time
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.update_ip
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private String updateIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.status
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.ts
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_street.district_gb_code
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    private String districtGbCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.id
     *
     * @return the value of info_street.id
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.id
     *
     * @param id the value for info_street.id
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.area_id
     *
     * @return the value of info_street.area_id
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.area_id
     *
     * @param areaId the value for info_street.area_id
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.code
     *
     * @return the value of info_street.code
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.code
     *
     * @param code the value for info_street.code
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.name
     *
     * @return the value of info_street.name
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.name
     *
     * @param name the value for info_street.name
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.create_user
     *
     * @return the value of info_street.create_user
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.create_user
     *
     * @param createUser the value for info_street.create_user
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.create_time
     *
     * @return the value of info_street.create_time
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.create_time
     *
     * @param createTime the value for info_street.create_time
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.create_ip
     *
     * @return the value of info_street.create_ip
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public String getCreateIp() {
        return createIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.create_ip
     *
     * @param createIp the value for info_street.create_ip
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setCreateIp(String createIp) {
        this.createIp = createIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.update_user
     *
     * @return the value of info_street.update_user
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.update_user
     *
     * @param updateUser the value for info_street.update_user
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.update_time
     *
     * @return the value of info_street.update_time
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.update_time
     *
     * @param updateTime the value for info_street.update_time
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.update_ip
     *
     * @return the value of info_street.update_ip
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public String getUpdateIp() {
        return updateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.update_ip
     *
     * @param updateIp the value for info_street.update_ip
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setUpdateIp(String updateIp) {
        this.updateIp = updateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.status
     *
     * @return the value of info_street.status
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.status
     *
     * @param status the value for info_street.status
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.ts
     *
     * @return the value of info_street.ts
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.ts
     *
     * @param ts the value for info_street.ts
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_street.district_gb_code
     *
     * @return the value of info_street.district_gb_code
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public String getDistrictGbCode() {
        return districtGbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_street.district_gb_code
     *
     * @param districtGbCode the value for info_street.district_gb_code
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    public void setDistrictGbCode(String districtGbCode) {
        this.districtGbCode = districtGbCode;
    }
}