package com.yzw.platform.entity.user;

import java.io.Serializable;

public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.id
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USER_NAME_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.PASS_WORD_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private String passWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USERE_EMAIL_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private String usereEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USER_MOBILE_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private Integer userMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.SEX_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.SYS_ROLE_ID_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private Integer sysRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USER_STATUS_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.REGISTER_TIME_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private String registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.LAST_LOGIN_IP_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.LAST_LOGIN_TIME_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private String lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.DELTE_FLAG_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    private Integer delteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.id
     *
     * @return the value of t_user_info.id
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.id
     *
     * @param id the value for t_user_info.id
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USER_NAME_
     *
     * @return the value of t_user_info.USER_NAME_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USER_NAME_
     *
     * @param userName the value for t_user_info.USER_NAME_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.PASS_WORD_
     *
     * @return the value of t_user_info.PASS_WORD_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.PASS_WORD_
     *
     * @param passWord the value for t_user_info.PASS_WORD_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USERE_EMAIL_
     *
     * @return the value of t_user_info.USERE_EMAIL_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public String getUsereEmail() {
        return usereEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USERE_EMAIL_
     *
     * @param usereEmail the value for t_user_info.USERE_EMAIL_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setUsereEmail(String usereEmail) {
        this.usereEmail = usereEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USER_MOBILE_
     *
     * @return the value of t_user_info.USER_MOBILE_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public Integer getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USER_MOBILE_
     *
     * @param userMobile the value for t_user_info.USER_MOBILE_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setUserMobile(Integer userMobile) {
        this.userMobile = userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.SEX_
     *
     * @return the value of t_user_info.SEX_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.SEX_
     *
     * @param sex the value for t_user_info.SEX_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.SYS_ROLE_ID_
     *
     * @return the value of t_user_info.SYS_ROLE_ID_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public Integer getSysRoleId() {
        return sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.SYS_ROLE_ID_
     *
     * @param sysRoleId the value for t_user_info.SYS_ROLE_ID_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setSysRoleId(Integer sysRoleId) {
        this.sysRoleId = sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USER_STATUS_
     *
     * @return the value of t_user_info.USER_STATUS_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USER_STATUS_
     *
     * @param userStatus the value for t_user_info.USER_STATUS_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.REGISTER_TIME_
     *
     * @return the value of t_user_info.REGISTER_TIME_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public String getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.REGISTER_TIME_
     *
     * @param registerTime the value for t_user_info.REGISTER_TIME_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setRegisterTime(String registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.LAST_LOGIN_IP_
     *
     * @return the value of t_user_info.LAST_LOGIN_IP_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.LAST_LOGIN_IP_
     *
     * @param lastLoginIp the value for t_user_info.LAST_LOGIN_IP_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.LAST_LOGIN_TIME_
     *
     * @return the value of t_user_info.LAST_LOGIN_TIME_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public String getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.LAST_LOGIN_TIME_
     *
     * @param lastLoginTime the value for t_user_info.LAST_LOGIN_TIME_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setLastLoginTime(String lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.DELTE_FLAG_
     *
     * @return the value of t_user_info.DELTE_FLAG_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public Integer getDelteFlag() {
        return delteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.DELTE_FLAG_
     *
     * @param delteFlag the value for t_user_info.DELTE_FLAG_
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    public void setDelteFlag(Integer delteFlag) {
        this.delteFlag = delteFlag;
    }
}