package com.yzw.platform.entity.user;

import java.io.Serializable;
import java.util.Date;

public class VillageQk implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.prc_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer prcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.lm_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer lmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.cea_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer ceaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.Adjacent_District
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String adjacentDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.Longitude
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.Latitude
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.valliage_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String valliageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.subway
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String subway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.subway_distance
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer subwayDistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.traffic
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String traffic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.shopping
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String shopping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.leisure
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String leisure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.hospital
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String hospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.create_time
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.Adjacent_District_prcId
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer adjacentDistrictPrcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.Village_Adress
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String villageAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.namePinyin
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String namepinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.street_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer streetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.street_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String streetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.block_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String blockName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.colse_block_info
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String colseBlockInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.policeStation_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer policestationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.policeStation_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String policestationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.service_center_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer serviceCenterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.service_center_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String serviceCenterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.cb_desc
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String cbDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.property_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String propertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.property_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String propertyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.gas_corp_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String gasCorpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.gas_corp_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String gasCorpPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.tv_service_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String tvServiceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.tv_service_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String tvServicePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.net_service_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String netServiceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.net_service_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String netServicePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.electric_corp_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String electricCorpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.electric_corp_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String electricCorpPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.water_corp_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String waterCorpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.water_corp_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String waterCorpPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.schools
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String schools;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.vegetables_markets
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String vegetablesMarkets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.banks
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String banks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.post_office
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String postOffice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.others
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.bus
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String bus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.approval_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer approvalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.approval_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String approvalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.approval_time
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Date approvalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.datastatus
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer datastatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.timemark
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String timemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.status
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.address_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.areaid
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.ceaid
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer ceaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.corp
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer corp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.region
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.cbPic
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String cbpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.fy_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer fyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.apartment_type
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Integer apartmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.UpdateTime
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Long updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.ts
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Village_Qk_yzw.name_alias
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    private String nameAlias;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.id
     *
     * @return the value of Village_Qk_yzw.id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.id
     *
     * @param id the value for Village_Qk_yzw.id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.name
     *
     * @return the value of Village_Qk_yzw.name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.name
     *
     * @param name the value for Village_Qk_yzw.name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.prc_id
     *
     * @return the value of Village_Qk_yzw.prc_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getPrcId() {
        return prcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.prc_id
     *
     * @param prcId the value for Village_Qk_yzw.prc_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setPrcId(Integer prcId) {
        this.prcId = prcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.lm_id
     *
     * @return the value of Village_Qk_yzw.lm_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getLmId() {
        return lmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.lm_id
     *
     * @param lmId the value for Village_Qk_yzw.lm_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setLmId(Integer lmId) {
        this.lmId = lmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.cea_id
     *
     * @return the value of Village_Qk_yzw.cea_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getCeaId() {
        return ceaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.cea_id
     *
     * @param ceaId the value for Village_Qk_yzw.cea_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setCeaId(Integer ceaId) {
        this.ceaId = ceaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.Adjacent_District
     *
     * @return the value of Village_Qk_yzw.Adjacent_District
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getAdjacentDistrict() {
        return adjacentDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.Adjacent_District
     *
     * @param adjacentDistrict the value for Village_Qk_yzw.Adjacent_District
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setAdjacentDistrict(String adjacentDistrict) {
        this.adjacentDistrict = adjacentDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.Longitude
     *
     * @return the value of Village_Qk_yzw.Longitude
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.Longitude
     *
     * @param longitude the value for Village_Qk_yzw.Longitude
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.Latitude
     *
     * @return the value of Village_Qk_yzw.Latitude
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.Latitude
     *
     * @param latitude the value for Village_Qk_yzw.Latitude
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.valliage_name
     *
     * @return the value of Village_Qk_yzw.valliage_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getValliageName() {
        return valliageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.valliage_name
     *
     * @param valliageName the value for Village_Qk_yzw.valliage_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setValliageName(String valliageName) {
        this.valliageName = valliageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.subway
     *
     * @return the value of Village_Qk_yzw.subway
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getSubway() {
        return subway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.subway
     *
     * @param subway the value for Village_Qk_yzw.subway
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setSubway(String subway) {
        this.subway = subway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.subway_distance
     *
     * @return the value of Village_Qk_yzw.subway_distance
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getSubwayDistance() {
        return subwayDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.subway_distance
     *
     * @param subwayDistance the value for Village_Qk_yzw.subway_distance
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setSubwayDistance(Integer subwayDistance) {
        this.subwayDistance = subwayDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.traffic
     *
     * @return the value of Village_Qk_yzw.traffic
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.traffic
     *
     * @param traffic the value for Village_Qk_yzw.traffic
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setTraffic(String traffic) {
        this.traffic = traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.shopping
     *
     * @return the value of Village_Qk_yzw.shopping
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getShopping() {
        return shopping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.shopping
     *
     * @param shopping the value for Village_Qk_yzw.shopping
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setShopping(String shopping) {
        this.shopping = shopping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.leisure
     *
     * @return the value of Village_Qk_yzw.leisure
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getLeisure() {
        return leisure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.leisure
     *
     * @param leisure the value for Village_Qk_yzw.leisure
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setLeisure(String leisure) {
        this.leisure = leisure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.hospital
     *
     * @return the value of Village_Qk_yzw.hospital
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.hospital
     *
     * @param hospital the value for Village_Qk_yzw.hospital
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setHospital(String hospital) {
        this.hospital = hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.create_time
     *
     * @return the value of Village_Qk_yzw.create_time
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.create_time
     *
     * @param createTime the value for Village_Qk_yzw.create_time
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.Adjacent_District_prcId
     *
     * @return the value of Village_Qk_yzw.Adjacent_District_prcId
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getAdjacentDistrictPrcid() {
        return adjacentDistrictPrcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.Adjacent_District_prcId
     *
     * @param adjacentDistrictPrcid the value for Village_Qk_yzw.Adjacent_District_prcId
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setAdjacentDistrictPrcid(Integer adjacentDistrictPrcid) {
        this.adjacentDistrictPrcid = adjacentDistrictPrcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.Village_Adress
     *
     * @return the value of Village_Qk_yzw.Village_Adress
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getVillageAdress() {
        return villageAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.Village_Adress
     *
     * @param villageAdress the value for Village_Qk_yzw.Village_Adress
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setVillageAdress(String villageAdress) {
        this.villageAdress = villageAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.namePinyin
     *
     * @return the value of Village_Qk_yzw.namePinyin
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getNamepinyin() {
        return namepinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.namePinyin
     *
     * @param namepinyin the value for Village_Qk_yzw.namePinyin
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setNamepinyin(String namepinyin) {
        this.namepinyin = namepinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.street_id
     *
     * @return the value of Village_Qk_yzw.street_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getStreetId() {
        return streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.street_id
     *
     * @param streetId the value for Village_Qk_yzw.street_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setStreetId(Integer streetId) {
        this.streetId = streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.street_name
     *
     * @return the value of Village_Qk_yzw.street_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.street_name
     *
     * @param streetName the value for Village_Qk_yzw.street_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.block_name
     *
     * @return the value of Village_Qk_yzw.block_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getBlockName() {
        return blockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.block_name
     *
     * @param blockName the value for Village_Qk_yzw.block_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setBlockName(String blockName) {
        this.blockName = blockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.colse_block_info
     *
     * @return the value of Village_Qk_yzw.colse_block_info
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getColseBlockInfo() {
        return colseBlockInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.colse_block_info
     *
     * @param colseBlockInfo the value for Village_Qk_yzw.colse_block_info
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setColseBlockInfo(String colseBlockInfo) {
        this.colseBlockInfo = colseBlockInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.policeStation_id
     *
     * @return the value of Village_Qk_yzw.policeStation_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getPolicestationId() {
        return policestationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.policeStation_id
     *
     * @param policestationId the value for Village_Qk_yzw.policeStation_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setPolicestationId(Integer policestationId) {
        this.policestationId = policestationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.policeStation_name
     *
     * @return the value of Village_Qk_yzw.policeStation_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getPolicestationName() {
        return policestationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.policeStation_name
     *
     * @param policestationName the value for Village_Qk_yzw.policeStation_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setPolicestationName(String policestationName) {
        this.policestationName = policestationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.service_center_id
     *
     * @return the value of Village_Qk_yzw.service_center_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getServiceCenterId() {
        return serviceCenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.service_center_id
     *
     * @param serviceCenterId the value for Village_Qk_yzw.service_center_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setServiceCenterId(Integer serviceCenterId) {
        this.serviceCenterId = serviceCenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.service_center_name
     *
     * @return the value of Village_Qk_yzw.service_center_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getServiceCenterName() {
        return serviceCenterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.service_center_name
     *
     * @param serviceCenterName the value for Village_Qk_yzw.service_center_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setServiceCenterName(String serviceCenterName) {
        this.serviceCenterName = serviceCenterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.cb_desc
     *
     * @return the value of Village_Qk_yzw.cb_desc
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getCbDesc() {
        return cbDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.cb_desc
     *
     * @param cbDesc the value for Village_Qk_yzw.cb_desc
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setCbDesc(String cbDesc) {
        this.cbDesc = cbDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.property_name
     *
     * @return the value of Village_Qk_yzw.property_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.property_name
     *
     * @param propertyName the value for Village_Qk_yzw.property_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.property_phone
     *
     * @return the value of Village_Qk_yzw.property_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getPropertyPhone() {
        return propertyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.property_phone
     *
     * @param propertyPhone the value for Village_Qk_yzw.property_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setPropertyPhone(String propertyPhone) {
        this.propertyPhone = propertyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.gas_corp_name
     *
     * @return the value of Village_Qk_yzw.gas_corp_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getGasCorpName() {
        return gasCorpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.gas_corp_name
     *
     * @param gasCorpName the value for Village_Qk_yzw.gas_corp_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setGasCorpName(String gasCorpName) {
        this.gasCorpName = gasCorpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.gas_corp_phone
     *
     * @return the value of Village_Qk_yzw.gas_corp_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getGasCorpPhone() {
        return gasCorpPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.gas_corp_phone
     *
     * @param gasCorpPhone the value for Village_Qk_yzw.gas_corp_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setGasCorpPhone(String gasCorpPhone) {
        this.gasCorpPhone = gasCorpPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.tv_service_name
     *
     * @return the value of Village_Qk_yzw.tv_service_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getTvServiceName() {
        return tvServiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.tv_service_name
     *
     * @param tvServiceName the value for Village_Qk_yzw.tv_service_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setTvServiceName(String tvServiceName) {
        this.tvServiceName = tvServiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.tv_service_phone
     *
     * @return the value of Village_Qk_yzw.tv_service_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getTvServicePhone() {
        return tvServicePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.tv_service_phone
     *
     * @param tvServicePhone the value for Village_Qk_yzw.tv_service_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setTvServicePhone(String tvServicePhone) {
        this.tvServicePhone = tvServicePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.net_service_name
     *
     * @return the value of Village_Qk_yzw.net_service_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getNetServiceName() {
        return netServiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.net_service_name
     *
     * @param netServiceName the value for Village_Qk_yzw.net_service_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setNetServiceName(String netServiceName) {
        this.netServiceName = netServiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.net_service_phone
     *
     * @return the value of Village_Qk_yzw.net_service_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getNetServicePhone() {
        return netServicePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.net_service_phone
     *
     * @param netServicePhone the value for Village_Qk_yzw.net_service_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setNetServicePhone(String netServicePhone) {
        this.netServicePhone = netServicePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.electric_corp_name
     *
     * @return the value of Village_Qk_yzw.electric_corp_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getElectricCorpName() {
        return electricCorpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.electric_corp_name
     *
     * @param electricCorpName the value for Village_Qk_yzw.electric_corp_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setElectricCorpName(String electricCorpName) {
        this.electricCorpName = electricCorpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.electric_corp_phone
     *
     * @return the value of Village_Qk_yzw.electric_corp_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getElectricCorpPhone() {
        return electricCorpPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.electric_corp_phone
     *
     * @param electricCorpPhone the value for Village_Qk_yzw.electric_corp_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setElectricCorpPhone(String electricCorpPhone) {
        this.electricCorpPhone = electricCorpPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.water_corp_name
     *
     * @return the value of Village_Qk_yzw.water_corp_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getWaterCorpName() {
        return waterCorpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.water_corp_name
     *
     * @param waterCorpName the value for Village_Qk_yzw.water_corp_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setWaterCorpName(String waterCorpName) {
        this.waterCorpName = waterCorpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.water_corp_phone
     *
     * @return the value of Village_Qk_yzw.water_corp_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getWaterCorpPhone() {
        return waterCorpPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.water_corp_phone
     *
     * @param waterCorpPhone the value for Village_Qk_yzw.water_corp_phone
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setWaterCorpPhone(String waterCorpPhone) {
        this.waterCorpPhone = waterCorpPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.schools
     *
     * @return the value of Village_Qk_yzw.schools
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getSchools() {
        return schools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.schools
     *
     * @param schools the value for Village_Qk_yzw.schools
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setSchools(String schools) {
        this.schools = schools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.vegetables_markets
     *
     * @return the value of Village_Qk_yzw.vegetables_markets
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getVegetablesMarkets() {
        return vegetablesMarkets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.vegetables_markets
     *
     * @param vegetablesMarkets the value for Village_Qk_yzw.vegetables_markets
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setVegetablesMarkets(String vegetablesMarkets) {
        this.vegetablesMarkets = vegetablesMarkets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.banks
     *
     * @return the value of Village_Qk_yzw.banks
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getBanks() {
        return banks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.banks
     *
     * @param banks the value for Village_Qk_yzw.banks
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setBanks(String banks) {
        this.banks = banks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.post_office
     *
     * @return the value of Village_Qk_yzw.post_office
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getPostOffice() {
        return postOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.post_office
     *
     * @param postOffice the value for Village_Qk_yzw.post_office
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setPostOffice(String postOffice) {
        this.postOffice = postOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.others
     *
     * @return the value of Village_Qk_yzw.others
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.others
     *
     * @param others the value for Village_Qk_yzw.others
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setOthers(String others) {
        this.others = others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.bus
     *
     * @return the value of Village_Qk_yzw.bus
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getBus() {
        return bus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.bus
     *
     * @param bus the value for Village_Qk_yzw.bus
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setBus(String bus) {
        this.bus = bus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.approval_id
     *
     * @return the value of Village_Qk_yzw.approval_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getApprovalId() {
        return approvalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.approval_id
     *
     * @param approvalId the value for Village_Qk_yzw.approval_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setApprovalId(Integer approvalId) {
        this.approvalId = approvalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.approval_name
     *
     * @return the value of Village_Qk_yzw.approval_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getApprovalName() {
        return approvalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.approval_name
     *
     * @param approvalName the value for Village_Qk_yzw.approval_name
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setApprovalName(String approvalName) {
        this.approvalName = approvalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.approval_time
     *
     * @return the value of Village_Qk_yzw.approval_time
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Date getApprovalTime() {
        return approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.approval_time
     *
     * @param approvalTime the value for Village_Qk_yzw.approval_time
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setApprovalTime(Date approvalTime) {
        this.approvalTime = approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.datastatus
     *
     * @return the value of Village_Qk_yzw.datastatus
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getDatastatus() {
        return datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.datastatus
     *
     * @param datastatus the value for Village_Qk_yzw.datastatus
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setDatastatus(Integer datastatus) {
        this.datastatus = datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.timemark
     *
     * @return the value of Village_Qk_yzw.timemark
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getTimemark() {
        return timemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.timemark
     *
     * @param timemark the value for Village_Qk_yzw.timemark
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setTimemark(String timemark) {
        this.timemark = timemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.status
     *
     * @return the value of Village_Qk_yzw.status
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.status
     *
     * @param status the value for Village_Qk_yzw.status
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.address_id
     *
     * @return the value of Village_Qk_yzw.address_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.address_id
     *
     * @param addressId the value for Village_Qk_yzw.address_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.areaid
     *
     * @return the value of Village_Qk_yzw.areaid
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.areaid
     *
     * @param areaid the value for Village_Qk_yzw.areaid
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.ceaid
     *
     * @return the value of Village_Qk_yzw.ceaid
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getCeaid() {
        return ceaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.ceaid
     *
     * @param ceaid the value for Village_Qk_yzw.ceaid
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setCeaid(Integer ceaid) {
        this.ceaid = ceaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.corp
     *
     * @return the value of Village_Qk_yzw.corp
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getCorp() {
        return corp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.corp
     *
     * @param corp the value for Village_Qk_yzw.corp
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setCorp(Integer corp) {
        this.corp = corp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.region
     *
     * @return the value of Village_Qk_yzw.region
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.region
     *
     * @param region the value for Village_Qk_yzw.region
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setRegion(Integer region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.cbPic
     *
     * @return the value of Village_Qk_yzw.cbPic
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getCbpic() {
        return cbpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.cbPic
     *
     * @param cbpic the value for Village_Qk_yzw.cbPic
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setCbpic(String cbpic) {
        this.cbpic = cbpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.fy_id
     *
     * @return the value of Village_Qk_yzw.fy_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getFyId() {
        return fyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.fy_id
     *
     * @param fyId the value for Village_Qk_yzw.fy_id
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setFyId(Integer fyId) {
        this.fyId = fyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.apartment_type
     *
     * @return the value of Village_Qk_yzw.apartment_type
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Integer getApartmentType() {
        return apartmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.apartment_type
     *
     * @param apartmentType the value for Village_Qk_yzw.apartment_type
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setApartmentType(Integer apartmentType) {
        this.apartmentType = apartmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.UpdateTime
     *
     * @return the value of Village_Qk_yzw.UpdateTime
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Long getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.UpdateTime
     *
     * @param updatetime the value for Village_Qk_yzw.UpdateTime
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setUpdatetime(Long updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.ts
     *
     * @return the value of Village_Qk_yzw.ts
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.ts
     *
     * @param ts the value for Village_Qk_yzw.ts
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Village_Qk_yzw.name_alias
     *
     * @return the value of Village_Qk_yzw.name_alias
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public String getNameAlias() {
        return nameAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Village_Qk_yzw.name_alias
     *
     * @param nameAlias the value for Village_Qk_yzw.name_alias
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    public void setNameAlias(String nameAlias) {
        this.nameAlias = nameAlias;
    }
}