package com.yzw.platform.dao.user;

import com.yzw.platform.entity.user.InfoStreet;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("infoStreetMapper")
public interface InfoStreetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_street
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_street
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    int insert(InfoStreet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_street
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    InfoStreet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_street
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    List<InfoStreet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_street
     *
     * @mbg.generated Wed Jul 03 14:23:02 CST 2019
     */
    int updateByPrimaryKey(InfoStreet record);

    void insertForeachStreet(List<InfoStreet> infoStreet);

    List<InfoStreet> selectInfoStreet(String streetName);

}