package com.yzw.platform.dao.user;

import com.yzw.platform.entity.user.InfoRole;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("infoRoleMapper")
public interface InfoRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Fri Jul 12 15:55:26 CST 2019
     */
    int deleteByPrimaryKey(Long rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Fri Jul 12 15:55:26 CST 2019
     */
    int insert(InfoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Fri Jul 12 15:55:26 CST 2019
     */
    InfoRole selectByPrimaryKey(Long rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Fri Jul 12 15:55:26 CST 2019
     */
    List<InfoRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Fri Jul 12 15:55:26 CST 2019
     */
    int updateByPrimaryKey(InfoRole record);

    List<InfoRole> selectRoleByUserId(Long uId);
}