package com.yzw.platform.dao.user;

import com.yzw.platform.entity.user.VillageQk;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("villageQkMapper")
public interface VillageQkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Village_Qk_yzw
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Village_Qk_yzw
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    int insert(VillageQk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Village_Qk_yzw
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    VillageQk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Village_Qk_yzw
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    List<VillageQk> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Village_Qk_yzw
     *
     * @mbg.generated Thu Jul 04 11:06:33 CST 2019
     */
    int updateByPrimaryKey(VillageQk record);

    List<VillageQk> selectByVillageName(String villageName);
}