package com.yzw.platform.dao.mysql.user;

import com.yzw.platform.entity.user.UserInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("userInfoMapper")
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    UserInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Fri May 10 16:24:22 CST 2019
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     * 根据用户名查询用户信息
     * @param userName
     * @return UserInfo
     */
    UserInfo selectUserByName(String userName);
}